// Code generated by counterfeiter. DO NOT EDIT.
package fake

import (
	"context"
	"sync"

	connect "github.com/bufbuild/connect-go"
	"github.com/ralch/connect/internal/proto/connect/runtime/v1/runtimev1connect"
)

type FakeEventServiceHandler struct {
	PushEventStub        func(context.Context, *connect.Request[PushEventRequest]) (*connect.Response[PushEventResponse], error)
	pushEventMutex       sync.RWMutex
	pushEventArgsForCall []struct {
		arg1 context.Context
		arg2 *connect.Request[PushEventRequest]
	}
	pushEventReturns struct {
		result1 *connect.Response[PushEventResponse]
		result2 error
	}
	pushEventReturnsOnCall map[int]struct {
		result1 *connect.Response[PushEventResponse]
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeEventServiceHandler) PushEvent(arg1 context.Context, arg2 *connect.Request[PushEventRequest]) (*connect.Response[PushEventResponse], error) {
	fake.pushEventMutex.Lock()
	ret, specificReturn := fake.pushEventReturnsOnCall[len(fake.pushEventArgsForCall)]
	fake.pushEventArgsForCall = append(fake.pushEventArgsForCall, struct {
		arg1 context.Context
		arg2 *connect.Request[PushEventRequest]
	}{arg1, arg2})
	stub := fake.PushEventStub
	fakeReturns := fake.pushEventReturns
	fake.recordInvocation("PushEvent", []interface{}{arg1, arg2})
	fake.pushEventMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeEventServiceHandler) PushEventCallCount() int {
	fake.pushEventMutex.RLock()
	defer fake.pushEventMutex.RUnlock()
	return len(fake.pushEventArgsForCall)
}

func (fake *FakeEventServiceHandler) PushEventCalls(stub func(context.Context, *connect.Request[PushEventRequest]) (*connect.Response[PushEventResponse], error)) {
	fake.pushEventMutex.Lock()
	defer fake.pushEventMutex.Unlock()
	fake.PushEventStub = stub
}

func (fake *FakeEventServiceHandler) PushEventArgsForCall(i int) (context.Context, *connect.Request[PushEventRequest]) {
	fake.pushEventMutex.RLock()
	defer fake.pushEventMutex.RUnlock()
	argsForCall := fake.pushEventArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeEventServiceHandler) PushEventReturns(result1 *connect.Response[PushEventResponse], result2 error) {
	fake.pushEventMutex.Lock()
	defer fake.pushEventMutex.Unlock()
	fake.PushEventStub = nil
	fake.pushEventReturns = struct {
		result1 *connect.Response[PushEventResponse]
		result2 error
	}{result1, result2}
}

func (fake *FakeEventServiceHandler) PushEventReturnsOnCall(i int, result1 *connect.Response[PushEventResponse], result2 error) {
	fake.pushEventMutex.Lock()
	defer fake.pushEventMutex.Unlock()
	fake.PushEventStub = nil
	if fake.pushEventReturnsOnCall == nil {
		fake.pushEventReturnsOnCall = make(map[int]struct {
			result1 *connect.Response[PushEventResponse]
			result2 error
		})
	}
	fake.pushEventReturnsOnCall[i] = struct {
		result1 *connect.Response[PushEventResponse]
		result2 error
	}{result1, result2}
}

func (fake *FakeEventServiceHandler) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.pushEventMutex.RLock()
	defer fake.pushEventMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeEventServiceHandler) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ runtimev1connect.EventServiceHandler = new(FakeEventServiceHandler)
